spring:
  profiles:
    active: dev


############################ dev ##############################
---
spring:
  profiles: dev
  cloud:
    config:
      discovery:
        enabled: true
# eureka 配置
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://192.168.31.20:${server.port}/eureka/


############################ docker ##############################
---
spring:
  profiles: docker
  cloud:
    config:
      discovery:
        enabled: true
# eureka 配置
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-service:${server.port}/eureka/
